// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySanPham.Data;

#nullable disable

namespace QuanLySanPham.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030160748_DLSPham")]
    partial class DLSPham
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySanPham.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Laptop hiệu suất cao",
                            Name = "Laptop Dell",
                            Price = 20000000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Chuột không dây",
                            Name = "Chuột Logitech",
                            Price = 500000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bình giữ nhiệt",
                            Name = "Bình giữ nhiệt",
                            Price = 500000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tác phẩm kinh điển về nghệ thuật ứng xử và giao tiếp",
                            Name = "Sách - Đắc Nhân Tâm",
                            Price = 89000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tiểu thuyết triết lý nổi tiếng của Paulo Coelho",
                            Name = "Sách - Nhà Giả Kim",
                            Price = 99000m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 6,
                            Description = "Đồ chơi sáng tạo, giúp phát triển tư duy trẻ nhỏ",
                            Name = "Bộ Lego Classic 500 chi tiết",
                            Price = 850000m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 7,
                            Description = "Chất liệu mềm mịn, đáng yêu, phù hợp làm quà tặng",
                            Name = "Gấu bông Brown Line Friends 60cm",
                            Price = 350000m,
                            Stock = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
